# Generated by Django 5.2.7 on 2025-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
